import type { Market } from "../types";
import type { MarketplaceHours, MarketplaceListing } from "../types";

const WEEK: MarketplaceHours = {
  mon: ["09:00", "18:00"],
  tue: ["09:00", "18:00"],
  wed: ["09:00", "18:00"],
  thu: ["09:00", "18:00"],
  fri: ["09:00", "18:00"],
  sat: ["10:00", "16:00"],
  sun: null,
};

const ALWAYS: MarketplaceHours = {
  mon: ["00:00", "24:00"],
  tue: ["00:00", "24:00"],
  wed: ["00:00", "24:00"],
  thu: ["00:00", "24:00"],
  fri: ["00:00", "24:00"],
  sat: ["00:00", "24:00"],
  sun: ["00:00", "24:00"],
};

type Seed = Omit<
  MarketplaceListing,
  "distanceKm" | "openNow" | "ownerSub" | "status"
> & { status?: MarketplaceListing["status"] };

/** Founder-seeded directory. Public teaching hospitals + Mirror boutique IDs stay stable. */
export const MARKETPLACE_SEED: Seed[] = [
  {
    id: "lst-bloom",
    name: "Bloom Pharmacy",
    category: "pharmacy",
    market: "NG",
    address: "Ikeja, Lagos",
    phone: null,
    lat: 6.6018,
    lng: 3.3515,
    hours: WEEK,
    rating: 4.5,
    tags: ["period_care", "pain_relief", "pharmacy", "acne", "skincare"],
    services: ["pain relief", "period care", "skincare"],
    registrationNumber: "PCN-SEED",
    seeded: true,
    catalogueItemId: "sk-niacinamide",
    sponsored: false,
  },
  {
    id: "lst-ease-pharm",
    name: "Ease Atelier Pharmacy Desk",
    category: "pharmacy",
    market: "NG",
    address: "Victoria Island, Lagos",
    phone: null,
    lat: 6.4281,
    lng: 3.4219,
    hours: WEEK,
    rating: 4.3,
    tags: ["pharmacy", "ovulation", "folic", "period_care"],
    services: ["ovulation tests", "folic acid"],
    registrationNumber: "PCN-SEED",
    seeded: true,
    catalogueItemId: null,
    sponsored: false,
  },
  {
    id: "lst-ikeja-clinic",
    name: "Ikeja Primary Health Centre",
    category: "clinic",
    market: "NG",
    address: "Ikeja, Lagos",
    phone: null,
    lat: 6.6018,
    lng: 3.3515,
    hours: ALWAYS,
    rating: 4.1,
    tags: ["hospital", "maternity", "emergency", "obstetric_scan", "dermatology"],
    services: ["antenatal", "general clinic"],
    registrationNumber: "NG-SEED",
    seeded: true,
    catalogueItemId: null,
    sponsored: false,
  },
  {
    id: "lst-luth",
    name: "Lagos University Teaching Hospital",
    category: "clinic",
    market: "NG",
    address: "Idi-Araba, Lagos",
    phone: null,
    lat: 6.5172,
    lng: 3.3541,
    hours: ALWAYS,
    rating: 4.4,
    tags: ["hospital", "maternity", "emergency", "obstetric_scan"],
    services: ["maternity", "emergency"],
    registrationNumber: "NG-PUBLIC",
    seeded: true,
    catalogueItemId: null,
    sponsored: false,
  },
  {
    id: "lst-ease",
    name: "Ease Atelier",
    category: "boutique",
    market: "NG",
    address: "Victoria Island, Lagos",
    phone: null,
    lat: 6.4281,
    lng: 3.4219,
    hours: WEEK,
    rating: 4.6,
    tags: ["pmos", "apparel"],
    services: ["apparel", "try-on"],
    registrationNumber: null,
    seeded: true,
    catalogueItemId: "ap-knit-set",
    sponsored: false,
  },
  {
    id: "lst-wellness",
    name: "Wellness Shelf",
    category: "beauty",
    market: "GH",
    address: "Osu, Accra",
    phone: null,
    lat: 5.5554,
    lng: -0.1869,
    hours: WEEK,
    rating: 4.4,
    tags: ["texture", "redness", "moisture", "skincare", "acne"],
    services: ["moisturiser", "barrier care"],
    registrationNumber: null,
    seeded: true,
    catalogueItemId: "sk-barrier",
    sponsored: false,
  },
  {
    id: "lst-maternal",
    name: "Maternal Thread",
    category: "boutique",
    market: "GH",
    address: "Airport City, Accra",
    phone: null,
    lat: 5.6053,
    lng: -0.1774,
    hours: WEEK,
    rating: 4.7,
    tags: ["maternity", "apparel"],
    services: ["maternity apparel"],
    registrationNumber: null,
    seeded: true,
    catalogueItemId: "ap-wrap-dress",
    sponsored: false,
  },
  {
    id: "lst-osu-clinic",
    name: "Osu Community Clinic",
    category: "clinic",
    market: "GH",
    address: "Osu, Accra",
    phone: null,
    lat: 5.5554,
    lng: -0.1869,
    hours: ALWAYS,
    rating: 4.1,
    tags: ["hospital", "maternity", "emergency", "obstetric_scan", "dermatology"],
    services: ["antenatal", "general clinic"],
    registrationNumber: "GH-SEED",
    seeded: true,
    catalogueItemId: null,
    sponsored: false,
  },
  {
    id: "lst-korlebu",
    name: "Korle Bu Teaching Hospital",
    category: "clinic",
    market: "GH",
    address: "Korle Bu, Accra",
    phone: null,
    lat: 5.5375,
    lng: -0.2267,
    hours: ALWAYS,
    rating: 4.5,
    tags: ["hospital", "maternity", "emergency", "obstetric_scan"],
    services: ["maternity", "emergency"],
    registrationNumber: "GH-PUBLIC",
    seeded: true,
    catalogueItemId: null,
    sponsored: false,
  },
  {
    id: "lst-osu-pharm",
    name: "Osu Wellness Pharmacy",
    category: "pharmacy",
    market: "GH",
    address: "Osu, Accra",
    phone: null,
    lat: 5.5554,
    lng: -0.1869,
    hours: WEEK,
    rating: 4.2,
    tags: ["pharmacy", "period_care", "ovulation", "folic"],
    services: ["pharmacy"],
    registrationNumber: "GHS-SEED",
    seeded: true,
    catalogueItemId: null,
    sponsored: false,
  },
  {
    id: "lst-southken",
    name: "South Ken Beauty",
    category: "beauty",
    market: "UK",
    address: "South Kensington, London SW7",
    phone: null,
    lat: 51.4945,
    lng: -0.1743,
    hours: WEEK,
    rating: 4.6,
    tags: ["age_spot", "radiance", "skincare", "acne"],
    services: ["SPF", "skincare"],
    registrationNumber: null,
    seeded: true,
    catalogueItemId: "sk-spf",
    sponsored: false,
  },
  {
    id: "lst-chelsea",
    name: "Chelsea and Westminster Hospital",
    category: "clinic",
    market: "UK",
    address: "369 Fulham Road, London SW10 9NH",
    phone: "020 3315 8000",
    lat: 51.4822,
    lng: -0.1816,
    hours: ALWAYS,
    rating: 4.5,
    tags: ["hospital", "maternity", "emergency", "obstetric_scan"],
    services: ["maternity", "emergency"],
    registrationNumber: "CQC-PUBLIC",
    seeded: true,
    catalogueItemId: null,
    sponsored: false,
  },
  {
    id: "lst-sw7-pharm",
    name: "South Ken Pharmacy",
    category: "pharmacy",
    market: "UK",
    address: "South Kensington, London SW7",
    phone: null,
    lat: 51.4945,
    lng: -0.1743,
    hours: WEEK,
    rating: 4.3,
    tags: ["pharmacy", "period_care", "pain_relief", "ovulation", "folic"],
    services: ["pharmacy"],
    registrationNumber: "GPhC-SEED",
    seeded: true,
    catalogueItemId: null,
    sponsored: false,
  },
];

export function seededAsListing(seed: Seed): MarketplaceListing {
  return {
    ...seed,
    status: "live",
    distanceKm: null,
    openNow: null,
    ownerSub: null,
  };
}

export function defaultHours(): MarketplaceHours {
  return { ...WEEK };
}

export function tzForMarket(market: Market): string {
  if (market === "NG") return "Africa/Lagos";
  if (market === "GH") return "Africa/Accra";
  return "Europe/London";
}
