version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - cd infra-backend/modules/lambda/codes
      - npm ci
      - npm run typecheck
      - npm test || true
artifacts:
  files:
    - '**/*'
