/** Keep in sync with infra-backend/modules/lambda/functions.tf locals.functions. */
export const LAMBDA_NAMES = [
  "identity",
  "cycles",
  "pmos",
  "pregnancy",
  "ttc",
  "wallet",
  "wallet-share",
  "alena",
  "alena-guest",
  "healthlens",
  "healthlens-monthly",
  "mirror",
  "youcam-webhook",
  "wardrobe-intel",
  "resale",
  "marketplace",
  "library",
  "community",
  "notify",
  "notify-tick",
  "billing",
  "billing-webhooks",
  "privacy",
  "purge",
];
